server:
  port: 8081

jasypt:
  encryptor:
    bean: jasyptEncryptor
    property:
      prefix: ENC(
      suffix: )
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql.cj07fndkeuan.ap-northeast-2.rds.amazonaws.com:3306/order
    password: "!garak2446810"
    username: admin
#  h2:
#    console:
#      path: /h2-console
#      settings:
#        web-allow-others: true
#  datasource:
#    url: jdbc:h2:tcp://localhost/~/Desktop/h2/test
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver
  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    hibernate:
      ddl-auto: update