apiVersion: apps/v1
kind: Deployment
metadata:
  name: member-backend
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: member-backend
  template:
    metadata:
      labels:
        app: member-backend
    spec:
      containers:
        - name: member-backend
          image: 207797165735.dkr.ecr.ap-northeast-2.amazonaws.com/member:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
