apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-backend
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: order-backend
  template:
    metadata:
      labels:
        app: order-backend
    spec:
      containers:
        - name: order-backend
          image: 207797165735.dkr.ecr.ap-northeast-2.amazonaws.com/order:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
